# Generated by Django 4.0.3 on 2022-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_send_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_message',
            name='filter_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
