# Generated by Django 4.0.3 on 2022-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_send_message_filter_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_message',
            name='filter_message',
        ),
        migrations.RemoveField(
            model_name='send_message',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AlterField(
            model_name='send_message',
            name='recipient',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
