# Generated by Django 4.0.3 on 2022-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_send_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_message',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
